Objective: 

Use Subqueries, CTEs, and Window Functions to analyze sales data from the Superstore dataset.

Tasks 

Step 1: Setup Data 

Import the Superstore dataset into a table named superstore_raw.  

Create these 3 tables from it:  

customers  

orders  

products  

Insert data into these tables using SELECT DISTINCT.

In [1]:
import pandas as pd 
import sqlite3

* LOAD THE CSV DATASET

In [4]:
df=pd.read_csv('/Users/sanskriti/Desktop/sql_task3_project/Sample - Superstore.csv',encoding='latin1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [7]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [9]:
conn = sqlite3.connect("sales_analysis.db")

In [10]:
df.to_sql(
    "superstore_raw",
    conn,
    if_exists="replace",
    index=False
)

9994

In [11]:
pd.read_sql(
    "SELECT * FROM superstore_raw LIMIT 5",
    conn
)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

* CUSTOMER TABLE

In [14]:
conn.execute("""
             CREATE TABLE customers AS
             SELECT DISTINCT  
               "Customer ID" AS customer_id,
               "Customer Name" AS customer_name,
                Segment,
                Country,
                City,
                state,
                Region
             FROM superstore_raw;
             """)

In [15]:
pd.read_sql(
    "SELECT * FROM customers LIMIT 5",
    conn
)

,customer_id,customer_name,Segment,Country,City,State,Region
0,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South
1,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West
2,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
3,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
4,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,South

* PRODUCT TABLE

In [16]:
conn.execute("""
CREATE TABLE products AS
SELECT DISTINCT
    "Product ID" AS product_id,
    "Product Name" AS product_name,
    Category,
    "Sub-Category" AS sub_category
FROM superstore_raw;
""")

In [18]:
pd.read_sql(
    "SELECT * FROM products LIMIT 5",conn)

,product_id,product_name,Category,sub_category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

* ORDER TABLE

In [19]:
conn.execute("""
CREATE TABLE orders AS
SELECT
    "Order ID" AS order_id,
    "Order Date" AS order_date,
    "Ship Date" AS ship_date,
    "Ship Mode" AS ship_mode,
    "Customer ID" AS customer_id,
    "Product ID" AS product_id,
    Sales,
    Quantity,
    Discount,
    Profit
FROM superstore_raw;
""")

In [20]:
pd.read_sql("" \
"SELECT * FROM orders LIMIT 5",conn)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,OFF-LA-10000240,14.6200,2,0.00,6.8714
3,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,FUR-TA-10000577,957.5775,5,0.45,-383.0310
4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,OFF-ST-10000760,22.3680,2,0.20,2.5164

* verify tables

In [21]:
pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

             name
0  superstore_raw
1       customers
2        products
3          orders

Step 2: Perform Required Queries 

Write and execute SQL queries for each of the following: 

1.Find all orders where sales are greater than the average sales. (Subquery)  

2.Find the highest sales order for each customer. (Subquery)  

3.Calculate total sales for each customer. (CTE)  

4.Find customers whose total sales are above average. (CTE + Subquery)  

5.Rank all customers based on total sales. (Window Function)  

6.Assign row numbers to each order within a customer. (Window Function + PARTITION BY)  

7.Display top 3 customers based on total sales. (Window Function)

1.) Find all orders where sales are greater than the average sales. (Subquery)

In [23]:
pd.read_sql(
    """SELECT * 
    FROM orders
    WHERE sales>(
      SELECT AVG(Sales)
      FROM orders );
      """,conn)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,FUR-TA-10000577,957.5775,5,0.45,-383.0310
3,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,TEC-PH-10002275,907.1520,6,0.20,90.7152
4,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,FUR-TA-10001539,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...
2355,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,TEC-PH-10004080,271.9600,5,0.20,27.1960
2356,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,TEC-PH-10002496,249.5840,2,0.20,31.1980
2357,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,OFF-BI-10002026,437.4720,14,0.20,153.1152
2358,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,TEC-PH-10003645,258.5760,2,0.20,19.3932
2359,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,OFF-AP-10002684,243.1600,2,0.00,72.9480

2. Find the highest sales order for each customer (Subquery)

In [35]:
pd.read_sql("""
            SELECT customer_id, order_id,Sales
            FROM orders o
            WHERE sales=
            (
               SELECT MAX(SALES)
               FROM orders
               WHERE customer_id=o.customer_id
            );
            """,conn)

    customer_id        order_id      Sales
0      CG-12520  CA-2016-152156   731.9400
1      SO-20335  US-2015-108966   957.5775
2      BH-11710  CA-2014-115812  1706.1840
3      EB-13870  CA-2015-106320  1044.6300
4      TB-21520  US-2015-150630  3083.4300
..          ...             ...        ...
790    DH-13075  CA-2015-159534  1087.9360
791    IM-15055  CA-2016-129630  2799.9600
792    HW-14935  CA-2017-121559  2405.2000
793    RB-19435  CA-2017-153871   735.9800
794    AP-10720  US-2016-103674   437.4720

[795 rows x 3 columns]

3. Calculate total sales for each customer (CTE)

In [37]:
pd.read_sql("""
WITH customer_sales AS
(SELECT
        customer_id,
        SUM(Sales) AS total_sales
 FROM orders
 GROUP BY customer_id
)

SELECT *
FROM customer_sales
ORDER BY total_sales DESC; """,conn)

    customer_id  total_sales
0      SM-20320    25043.050
1      TC-20980    19052.218
2      RB-19360    15117.339
3      TA-21385    14595.620
4      AB-10105    14473.571
..          ...          ...
788    RS-19870       22.328
789    MG-18205       16.739
790    CJ-11875       16.520
791    LD-16855        5.304
792    TS-21085        4.833

[793 rows x 2 columns]

4. Find customers whose total sales are above average (CTE + Subquery)

In [38]:
pd.read_sql("""
WITH customer_sales AS 
(
            SELECT customer_id, 
            SUM(Sales) AS total_sales
            FROM orders
            GROUP BY customer_id
)
SELECT *
FROM customer_sales
WHERE total_sales>
            (
            SELECT AVG(total_sales)
            FROM customer_sales
            );
            """,conn)

    customer_id  total_sales
0      AA-10315     5563.560
1      AA-10645     5086.935
2      AB-10060     7755.620
3      AB-10105    14473.571
4      AC-10450     5527.846
..          ...          ...
289    VW-21775     6134.038
290    WB-21850     6160.102
291    YC-21895     5454.350
292    YS-21880     6720.444
293    ZC-21910     8025.707

[294 rows x 2 columns]

5. Rank all customers based on total sales (Window Function)

In [39]:
pd.read_sql("""
WITH customer_sales AS 
(
    SELECT customer_id , SUM(Sales) AS total_sales
    FROM orders 
    GROUP BY customer_id
) 
SELECT customer_id , total_sales, 
RANK() OVER( ORDER BY total_sales DESC) AS customer_rnk
FROM customer_sales;""",conn)

    customer_id  total_sales  customer_rnk
0      SM-20320    25043.050             1
1      TC-20980    19052.218             2
2      RB-19360    15117.339             3
3      TA-21385    14595.620             4
4      AB-10105    14473.571             5
..          ...          ...           ...
788    RS-19870       22.328           789
789    MG-18205       16.739           790
790    CJ-11875       16.520           791
791    LD-16855        5.304           792
792    TS-21085        4.833           793

[793 rows x 3 columns]

6. Assign row numbers to each order within a customer (PARTITION BY)

In [42]:
pd.read_sql("""
       SELECT customer_id , order_id, Sales,
       ROW_NUMBER() OVER(
              PARTITION BY customer_id
              ORDER BY Sales DESC) AS row_num
       FROM orders;
       """,conn)

     customer_id        order_id     Sales  row_num
0       AA-10315  CA-2016-103982  3930.072        1
1       AA-10315  CA-2014-128055   673.568        2
2       AA-10315  CA-2016-103982   431.976        3
3       AA-10315  CA-2017-147039   362.940        4
4       AA-10315  CA-2014-128055    52.980        5
...          ...             ...       ...      ...
9989    ZD-21925  CA-2017-141481    61.440        5
9990    ZD-21925  CA-2014-143336    22.720        6
9991    ZD-21925  US-2016-147991    16.720        7
9992    ZD-21925  CA-2016-152471    15.984        8
9993    ZD-21925  CA-2014-143336     8.560        9

[9994 rows x 4 columns]

7. Display Top 3 Customers Based on Total Sales (Window Function)

In [43]:
pd.read_sql("""
WITH customer_sales AS 
(
  SELECT customer_id, SUM(Sales) AS total_sales
  FROM orders
  GROUP BY customer_id
),
ranked_customers AS
(
    SELECT customer_id, total_sales,
    RANK() OVER(
            ORDER BY total_sales DESC) AS sales_rank 
    FROM customer_sales
)
SELECT *
FROM  ranked_customers
WHERE sales_rank<=3;

""",conn)

  customer_id  total_sales  sales_rank
0    SM-20320    25043.050           1
1    TC-20980    19052.218           2
2    RB-19360    15117.339           3

Step 3: Final Combined Query 

Write one final query that shows: 

Customer Name  

Total Sales  

Rank  

(Use JOIN + CTE + Window Function together)

In [44]:
pd.read_sql("""
SELECT name 
FROM sqlite_master
WHERE type='table'; 
""",conn)

             name
0  superstore_raw
1       customers
2        products
3          orders

In [45]:
pd.read_sql("""
PRAGMA table_info(customers);
""", conn)

   cid           name  type  notnull dflt_value  pk
0    0    customer_id  TEXT        0       None   0
1    1  customer_name  TEXT        0       None   0
2    2        Segment  TEXT        0       None   0
3    3        Country  TEXT        0       None   0
4    4           City  TEXT        0       None   0
5    5          State  TEXT        0       None   0
6    6         Region  TEXT        0       None   0

* FINAL COMBINED QUERY

In [54]:
final_result= pd.read_sql("""
WITH customer_sales AS
(
    SELECT c.customer_id, c.customer_name, SUM(o.Sales) AS total_sales
    FROM customers c
    JOIN orders o 
       ON c.customer_id=o.customer_id
    GROUP BY c.customer_id, c.customer_name
)
SELECT customer_name, total_sales,
      RANK() OVER(
                  ORDER BY total_sales DESC ) AS customer_rank 
FROM customer_sales;                          
""",conn)
final_result.head(20)

       customer_name  total_sales  customer_rank
0       Ken Lonsdale   141752.290              1
1       Sanjit Engle   134303.818              2
2      Adrian Barton   130262.139              3
3        Sean Miller   125215.250              4
4        Clay Ludtke   119686.006              5
5       Sanjit Chand   113138.672              6
6        Seth Vernon   103238.550              7
7   Zuschuss Carroll    96308.484              8
8      Maria Etezadi    95973.552              9
9    Laura Armstrong    95405.442             10
10      Tamara Chand    95261.090             11
11     Anna Häberlin    94659.528             12
12         Greg Tran    94560.960             13
13      Edward Hooks    92797.920             14
14      Raymond Buch    90704.034             15
15   Caroline Jumper    89319.792             16
16          John Lee    88199.307             17
17        Joel Eaton    87890.595             18
18         Pete Kriz    86469.340             19
19    Lena Creighton    84294.386             20

## Final Query Insight

The query combines JOIN, CTE, and Window Functions to identify the highest-value customers.

Customers with Rank 1 generate the highest total sales and are the most valuable customers for the business.

Mini Project: Customer Sales Insights 

Answer the following using SQL: 

1.)Who are the top 5 customers?  

2.)Who are the bottom 5 customers?  

3.)Which customers made only one order?  

4.)Which customers have above-average sales?  

5.)What is the highest order value per customer?

1.)Who are the top 5 customers?
Insight:

The top 5 customers contribute the highest revenue and represent the most valuable customer segment.

In [65]:
pd.read_sql("""
WITH customer_sales AS 
(
    SELECT c.customer_id, c.customer_name, SUM(o.Sales) AS total_sales
    FROM customers c
    JOIN orders o 
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.customer_name
)
SELECT *
FROM customer_sales
ORDER BY total_sales DESC 
LIMIT 5;
""",conn)

  customer_id  customer_name  total_sales
0    KL-16645   Ken Lonsdale   141752.290
1    SE-20110   Sanjit Engle   134303.818
2    AB-10105  Adrian Barton   130262.139
3    SM-20320    Sean Miller   125215.250
4    CL-12565    Clay Ludtke   119686.006

2.)Who are the bottom 5 customers?

In [56]:
pd.read_sql("""
WITH customer_sales AS
(
            SELECT c.customer_id, c.customer_name, SUM(o.Sales) AS total_sales 
            FROM customers c
            JOIN orders o 
                ON c.customer_id=o.customer_id
            GROUP BY c.customer_id, c.customer_name
)
SELECT *
FROM customer_sales 
ORDER BY total_sales ASC
LIMIT 5; 
""",conn)

  customer_id    customer_name  total_sales
0    LD-16855     Lela Donovan        5.304
1    TS-21085    Thais Sissman        9.666
2    CJ-11875     Carl Jackson       16.520
3    MG-18205  Mitch Gastineau       16.739
4    RS-19870       Roy Skaria       44.656

3.)Which customers made only one order? 
Insight:

These customers may be targeted through retention campaigns to encourage repeat purchases.

In [62]:
pd.read_sql("""SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS total_orders
               FROM customers c
               JOIN orders o 
                   ON c.customer_id = o.customer_id 
               GROUP BY c.customer_id, c.customer_name
               HAVING COUNT(o.order_id)=1;
            """,conn)

  customer_id      customer_name  total_orders
0    AO-10810  Anthony O'Donnell             1
1    CJ-11875       Carl Jackson             1
2    JR-15700     Jocasta Rupert             1
3    LD-16855       Lela Donovan             1
4    RE-19405    Ricardo Emerson             1

4.)Which customers have above-average sales? 
Insight:

Customers above the average sales threshold are strong candidates for loyalty and premium programs.

In [63]:
pd.read_sql("""
WITH customer_sales AS 
(
    SELECT c.customer_id , c.customer_name,SUM(o.Sales) AS total_sales 
    FROM customers c 
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.customer_name
)
SELECT *
FROM customer_sales 
WHERE total_sales>
    (
            SELECT AVG(total_sales)
            FROM customer_sales
    )
ORDER BY total_sales DESC;
""",conn)

    customer_id  customer_name  total_sales
0      KL-16645   Ken Lonsdale   141752.290
1      SE-20110   Sanjit Engle   134303.818
2      AB-10105  Adrian Barton   130262.139
3      SM-20320    Sean Miller   125215.250
4      CL-12565    Clay Ludtke   119686.006
..          ...            ...          ...
273    TS-21610   Troy Staebel    19742.968
274    BD-11605   Brian Dahlen    19730.826
275    FM-14215  Filia McAdams    19653.104
276    MH-17455  Mark Hamilton    19649.456
277    DL-12925    Daniel Lacy    19633.200

[278 rows x 3 columns]

5.)What is the highest order value per customer?

In [64]:
pd.read_sql("""
SELECT c.customer_id, c.customer_name, MAX(o.Sales) AS highest_order_value
FROM customers c
JOIN orders o
    ON c.customer_id= o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY highest_order_value DESC;
""",conn)

    customer_id    customer_name  highest_order_value
0      SM-20320      Sean Miller            22638.480
1      TC-20980     Tamara Chand            17499.950
2      RB-19360     Raymond Buch            13999.960
3      TA-21385     Tom Ashbrook            11199.968
4      HL-15040     Hunter Lopez            10499.970
..          ...              ...                  ...
788    CJ-11875     Carl Jackson               16.520
789    MG-18205  Mitch Gastineau               12.320
790    RS-19870       Roy Skaria                9.648
791    LD-16855     Lela Donovan                5.304
792    TS-21085    Thais Sissman                2.808

[793 rows x 3 columns]

Mini Project: Customer Sales Insights
1. Top 5 Customers

Calculated total sales for each customer and identified the top five revenue-generating customers.

Business Insight:
A small group of customers contributes a significant portion of total sales.

2. Bottom 5 Customers

Identified customers with the lowest total sales.

Business Insight:
These customers may require engagement strategies to increase purchases.

3. Customers With Only One Order

Identified customers who placed exactly one order.

Business Insight:
These customers represent potential retention opportunities.

4. Customers With Above-Average Sales

Identified customers whose sales exceed the overall customer sales average.

Business Insight:
These customers can be targeted for premium offers and loyalty programs.

5. Highest Order Value Per Customer

Calculated the maximum order value placed by each customer.

Business Insight:
Highlights each customer's purchasing potential.